var noname = {
	stateManager: StateManager,
	loader: Loader,
	loop: Loop,
	mathematics: Mathematics,
	time: Time,
	render: Render,
	world: World,
	audio: Audio,
	messages: Messages,
	camera: Camera,
	clockEvent: ClockEvent,
	track: Track,
	game: Game,
	state: State,
	clock: Clock,
	keys: Keys,
	pointers: Pointers,
	transformComponent: TransformComponent,
	imageComponent: ImageComponent,
	spriteComponent: SpriteComponent,
	tileSpriteComponent: TileSpriteComponent,
	bodyComponent: BodyComponent
};
