var noname = {
	stateManager: StateManager,
	assetManager: AssetManager,
	loopManager: LoopManager,
	mathManager: MathManager,
	timeManager: TimeManager,
	entityManager: EntityManager,
	renderManager: RenderManager,
	box2dManager: Box2dManager,
	audioManager: AudioManager,
	pubsub: PubSub,
	camera: Camera,
	timeEvent: TimeEvent,
	track: Track,
	game: Game,
	state: State,
	entity: Entity,
	clock: Clock,
	keys: Keys,
	fingers: Fingers,
	transformComponent: TransformComponent,
	imageComponent: ImageComponent,
	spriteComponent: SpriteComponent,
	tileSpriteComponent: TileSpriteComponent,
	box2dComponent: Box2dComponent
};
