var noname = {
    stateManager: StateManager,
    assetManager: AssetManager,
    loopManager: LoopManager,
    mathManager:MathManager,
    inputManager: InputManager,
    clockManager: ClockManager,
    entityManager: EntityManager,
    renderManager: RenderManager,
    box2dManager: Box2dManager,
    game: Game,
    state: State,
    entity: Entity,
    clock: Clock,
    keyboard: Keyboard,
    matrixComponent: MatrixComponent,
    imageComponent: ImageComponent,
    spriteComponent: SpriteComponent,
    tileSpriteComponent: TileSpriteComponent,
    cameraComponent: CameraComponent
};
